SELECT DISTINCT ?child ?parent FROM <#ri>
WHERE {
  { ?child <http://islandora.ca/ontology/relsext#isComponentOf>                    ?parent . } UNION
  { ?child <http://islandora.ca/ontology/relsext#isPageOf>                         ?parent . } UNION
  { ?child <info:fedora/fedora-system:def/relations-external#isConstituentOf>      ?parent . } UNION
  { ?child <info:fedora/fedora-system:def/relations-external#isMemberOf>           ?parent . } UNION
  { ?child <info:fedora/fedora-system:def/relations-external#isMemberOfCollection> ?parent . } UNION
  { ?child <info:fedora/fedora-system:def/relations-external#isPageOf>             ?parent ; }
}
